[package]
name = "rote_macros"
version = "0.1.0"
authors = ["David Kern <david@mju.io>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.24"
quote = "1.0.9"
syn = "1.0.65"
